server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securite?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
mybatis:
  configuration:
    map-underscore-to-camel-case: true